p8105\_hw3\_xl3141
================
Xinyuan Liu
10/15/2021

## Set options

``` r
library(tidyverse)
```

    ## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --

    ## v ggplot2 3.3.5     v purrr   0.3.4
    ## v tibble  3.1.4     v dplyr   1.0.7
    ## v tidyr   1.1.3     v stringr 1.4.0
    ## v readr   2.0.1     v forcats 0.5.1

    ## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

``` r
data("instacart")
ncol(instacart)
```

    ## [1] 15

``` r
nrow(instacart)
```

    ## [1] 1384617

``` r
instacart %>% 
  group_by(product_name) %>% 
  summarise(n_obs = n()) %>% 
  filter(n_obs == max(n_obs)) ##choose the most popular product
```

    ## # A tibble: 1 x 2
    ##   product_name n_obs
    ##   <chr>        <int>
    ## 1 Banana       18726

``` r
day_prior = instacart %>% 
  group_by(user_id) %>% 
  select(user_id, days_since_prior_order) %>% 
  unique() ##get the days since prior order for each unique user

mean(pull(day_prior, days_since_prior_order))
```

    ## [1] 17.04986

The data has 15 columns and 1384617 rows in total. The variables of
interest are *days since prior order*, *product name*, and *reordered*.
The product that is mostly bought is banana which is bought 18726 times
in total. The average days since prior order is 17 days.

``` r
instacart %>% 
  group_by(aisle) %>% 
  summarise(n_obs = n()) %>% ##count the number of aisles
  mutate(rank = rank(desc(n_obs))) %>% 
  filter(rank < 2) ##rank the numbers and find the largest one
```

    ## # A tibble: 1 x 3
    ##   aisle             n_obs  rank
    ##   <chr>             <int> <dbl>
    ## 1 fresh vegetables 150609     1

We have 134 aisles and most items are ordered from aisle “fresh
vegetables”.

``` r
instacart %>% 
  group_by(aisle, department) %>% 
  summarize(n_obs = n()) %>% 
  filter(n_obs > 10000) %>% ##get aisles with number > 10000
  relocate(department) %>% 
  ggplot(aes(x = aisle, y = n_obs, color = department)) +
  geom_point() +
  labs(
    title = "number of items purchased in each aisles",
    x = "aisle name",
    y = "number of times purchased"
  ) +
  theme(axis.text.x = element_text(size = 6, angle = 45))
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the `.groups` argument.

<img src="p8105_hw3_xl3141_files/figure-gfm/unnamed-chunk-4-1.png" width="90%" />

``` r
instacart %>% 
  group_by(aisle, product_name) %>% 
  filter(aisle == "baking ingredients") %>% ##look for baking ingredients in aisle column
  summarize(n_obs = n()) %>% 
  mutate(rank = rank(desc(n_obs))) %>% ##rank based on popularity
  filter(rank < 4) %>% 
  knitr::kable()
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the `.groups` argument.

| aisle              | product\_name     | n\_obs | rank |
|:-------------------|:------------------|-------:|-----:|
| baking ingredients | Cane Sugar        |    336 |    3 |
| baking ingredients | Light Brown Sugar |    499 |    1 |
| baking ingredients | Pure Baking Soda  |    387 |    2 |

``` r
instacart %>% 
  group_by(aisle, product_name) %>% 
  filter(aisle == "dog food care") %>% 
  summarize(n_obs = n()) %>% 
  mutate(rank = rank(desc(n_obs))) %>% 
  filter(rank < 4) %>% 
  knitr::kable()
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the `.groups` argument.

| aisle         | product\_name                                 | n\_obs | rank |
|:--------------|:----------------------------------------------|-------:|-----:|
| dog food care | Organix Chicken & Brown Rice Recipe           |     28 |    2 |
| dog food care | Small Dog Biscuits                            |     26 |    3 |
| dog food care | Snack Sticks Chicken & Rice Recipe Dog Treats |     30 |    1 |

``` r
instacart %>% 
  group_by(aisle, product_name) %>% 
  filter(aisle == "packaged vegetables fruits") %>% 
  summarize(n_obs = n()) %>% 
  mutate(rank = rank(desc(n_obs))) %>% 
  filter(rank < 4) %>%
  knitr::kable()
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the `.groups` argument.

| aisle                      | product\_name        | n\_obs | rank |
|:---------------------------|:---------------------|-------:|-----:|
| packaged vegetables fruits | Organic Baby Spinach |   9784 |    1 |
| packaged vegetables fruits | Organic Blueberries  |   4966 |    3 |
| packaged vegetables fruits | Organic Raspberries  |   5546 |    2 |

``` r
library(lubridate)
```

    ## 
    ## Attaching package: 'lubridate'

    ## The following objects are masked from 'package:base':
    ## 
    ##     date, intersect, setdiff, union

``` r
instacart %>% 
  group_by(product_name) %>% 
  mutate(
    order_dow = order_dow + 1,
    order_dow = wday(order_dow, label = TRUE)) %>% ##make number data into word
  select(order_dow, order_hour_of_day) %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>% 
  summarize(mean = mean(order_hour_of_day)) %>% ##calculate the mean hour of the day based on group "product name" and "order dow"
  pivot_wider(
    names_from = "order_dow",
    values_from = "mean"
    ) %>% 
  knitr::kable() ## make it into a 2*7 table
```

    ## Adding missing grouping variables: `product_name`

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

| product\_name    |      Sun |      Mon |      Tue |      Wed |      Thu |      Fri |      Sat |
|:-----------------|---------:|---------:|---------:|---------:|---------:|---------:|---------:|
| Coffee Ice Cream | 13.77419 | 14.31579 | 15.38095 | 15.31818 | 15.21739 | 12.26316 | 13.83333 |
| Pink Lady Apples | 13.44118 | 11.36000 | 11.70213 | 14.25000 | 11.55172 | 12.78431 | 11.93750 |
